#!/usr/bin/env python3
"""Makes the "closed eyes" and "wink" variants of the Kenney Cube Pets cat for the sleep buddy sprites.

The cat's eyes are flat orange polygons (with dark pupils) lying 0.01 in FRONT of the face plate at z = 0.635.
For the closed variant those polygons keep their exact shape, but get the fur's shading instead of the eye
colours: the UV points at the fur gradient of the face plate (colormap.png, u = 0.844, v 0.075 → 0.175 from the
bottom to the top of the plate) and the normals follow the plate's smooth normals, so under the same light they
look exactly like the face around them. The dark lash lines are added by the recipe (thin boxes).

Two variants are written:
  * animal-cat-closed – both eyes (every eye and pupil polygon) turned into fur;
  * animal-cat-wink   – only the cat's LEFT eye (polygon centroid x > 0, the cat faces +z) turned into fur, the
                        right eye stays open.

Output (git-ignored, regenerated by make_recipes.py): build/buddy/animal-cat-{closed,wink}.{obj,mtl} +
Textures/colormap.png
Run from the repo root:  python3 tools/render/buddy_cat_obj.py
"""
import math
import os
import shutil

SRC = "assets/Kenney Game Assets All-in-1 3/3D assets/Cube Pets/Models/OBJ format/"
OUT = "build/buddy/"

EYE_Z = 0.635          # the eye polygons
PLATE_Y0, PLATE_Y1 = 0.49375, 1.11875   # the raised front plate of the face
PLATE_N = 0.22 / 0.3125                  # plate normals: x -> nx, (y - mid) -> ny (affine, see the OBJ)
PLATE_MID = (PLATE_Y0 + PLATE_Y1) / 2
FUR_U, FUR_V0, FUR_V1 = 0.844, 0.075, 0.175


def fur_uv_normal(x, y):
    v = FUR_V0 + (FUR_V1 - FUR_V0) * (y - PLATE_Y0) / (PLATE_Y1 - PLATE_Y0)
    nx, ny = PLATE_N * x, PLATE_N * (y - PLATE_MID)
    nz = 0.95
    n = math.sqrt(nx * nx + ny * ny + nz * nz)
    return (FUR_U, v), (nx / n, ny / n, nz / n)


def main():
    V, VT, VN = [], [], []
    groups = []                      # (name, [face triples])
    for line in open(SRC + "animal-cat.obj"):
        p = line.split()
        if not p:
            continue
        if p[0] == "v":
            V.append(tuple(map(float, p[1:4])))
        elif p[0] == "vt":
            VT.append(tuple(map(float, p[1:3])))
        elif p[0] == "vn":
            VN.append(tuple(map(float, p[1:4])))
        elif p[0] == "g":
            groups.append((p[1], []))
        elif p[0] == "f":
            groups[-1][1].append([tuple(int(i) - 1 for i in t.split("/")) for t in p[1:]])

    os.makedirs(OUT + "Textures", exist_ok=True)
    shutil.copy(SRC + "Textures/colormap.png", OUT + "Textures/colormap.png")
    write_variant("closed", V, VT, VN, groups, lambda cx: True)
    write_variant("wink", V, VT, VN, groups, lambda cx: cx > 0)      # the cat's left eye (+x)


def write_variant(name, V, VT, VN, groups, pick):
    """Writes build/buddy/animal-cat-<name>.{obj,mtl}: every eye / pupil polygon whose centroid x passes
    `pick(cx)` gets the fur's UV + normals. The inputs are not modified."""
    VT, VN = list(VT), list(VN)
    groups = [(g, [list(f) for f in faces]) for g, faces in groups]
    cache = {}
    lids = 0
    for gname, faces in groups:
        if gname != "body":
            continue
        for f in faces:
            if all(abs(V[t[0]][2] - EYE_Z) < 0.002 for t in f) and pick(sum(V[t[0]][0] for t in f) / len(f)):
                lids += 1
                for k, (vi, ti, ni) in enumerate(f):
                    x, y, _ = V[vi]
                    if (x, y) not in cache:
                        uv, n = fur_uv_normal(x, y)
                        VT.append(uv); VN.append(n)
                        cache[(x, y)] = (len(VT) - 1, len(VN) - 1)
                    f[k] = (vi, cache[(x, y)][0], cache[(x, y)][1])
    assert lids > 20, lids

    shutil.copy(SRC + "animal-cat.mtl", OUT + f"animal-cat-{name}.mtl")
    with open(OUT + f"animal-cat-{name}.obj", "w") as o:
        o.write("# generated by tools/render/buddy_cat_obj.py from Kenney's animal-cat.obj (CC0)\n")
        o.write(f"mtllib animal-cat-{name}.mtl\n")
        for v in V:
            o.write("v %.7f %.7f %.7f\n" % v)
        for vt in VT:
            o.write("vt %.7f %.7f\n" % vt)
        for vn in VN:
            o.write("vn %.7f %.7f %.7f\n" % vn)
        for gname, faces in groups:
            o.write("g %s\nusemtl colormap\n" % gname)
            for f in faces:
                o.write("f " + " ".join("%d/%d/%d" % (a + 1, b + 1, c + 1) for a, b, c in f) + "\n")
    print(OUT + f"animal-cat-{name}.obj", "-", lids, "eye polygons turned into fur")


if __name__ == "__main__":
    main()
